sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install pylint
    - pip install Flask
    - pip3 install Flask
    - pip install Flask-SQLAlchemy
    - pip3 install Flask-SQLAlchemy
    - pip install -r app/requirements.txt

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test

notifications:
  slack: bestgrouptalk:cFeA058jovoo9CQxEo70eIdz