sudo: false

language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coveragey
    - pip install pylint
    - pip install flask
    - pip install flask-sqlalchemy

before_script:
    - uname -a
    - printenv | sort
    - make versions

script:
    - date
    - ls -al
    - make test

notifications:
  slack: bestgrouptalk:cFeA058jovoo9CQxEo70eIdz