FORMAT: 1A
HOST: http://ggnoswe.me/api
    
# Idb

GGnoSWE is an api that provides information for games, game developers, 
game reviews and platforms.

**Naming Conventions**

`Server:` **filler**

`Client: ` **filler**

## Games [/game]
Video games

### List All Games [GET]

+ Response 200 (application/json)

    + body
    
            [
                { 
                    "id": "0"
                    "name": "*PENDING*" 
    
                }
            ]
    
### List Specific Game [POST]

+ Response 200 (application/json)
    
            { 
                id : "Name"
                name:
                summary:""
                genre:
                rating:
                storyline:
                category:
                status:
                studio_id_fk:
                image:
                release_date:
                website: 
    
            }
        

## Platform [/platform]
Platforms

### List All Platforms [GET]

+ Response 200 (application/json)

    + body
    
            [
                { 
                    "id": "0",
                    "name": "*PENDING*" 
                },
                { 
                    "id": "1",
                    "name": "*PENDING*" 
                },
                { 
                    "id": "2",
                    "name": "*PENDING*" 
                }
            ]
    
### List Specific Platform [POST]

+ Response 200 (application/json)
    
            { 
                id : "Name"
                name:
                summary:""
                created_at:
                review:
                generation:
                image:
                website: 
    
            }
            

            
## Studio [/studio]
Game Studio

### List All Studios [GET]

+ Response 200 (application/json)

    + body
    
            [
                { 
                    "id": "0",
                    "name": "*PENDING*" 
                },
                { 
                    "id": "1",
                    "name": "*PENDING*" 
                },
                { 
                    "id": "2",
                    "name": "*PENDING*" 
                }
            ]
    
### List Specific Studio [POST]

+ Response 200 (application/json)
    
            { 
                id:
                name:
                platform:
                logo:
                description:
                game:
                published_Games:
                created_at:
                website:
            }
            

## Reviews [/reviews]
Platforms

### List All Reviews [GET]

+ Response 200 (application/json)

    + body
    
            [
                { 
                    "id": "0",
                    "name": "*PENDING*" 
                },
                { 
                    "id": "1",
                    "name": "*PENDING*" 
                },
                { 
                    "id": "2",
                    "name": "*PENDING*" 
                }
            ]
    
### List Specific Review [POST]

+ Response 200 (application/json)
    
            { 
                id:
                title:
                platform_id:
                game_id:
                created_at:
                views:
                video:
                introduction:
                content:
                conclusion:
                positive:
                negative:
                url:
    
            }